/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package facturacion.gui;

import facturacion.model.Pedido;
import facturacion.model.Producto;

/**
 *
 * @author SONY VAIO
 */
public class PanelProducto extends javax.swing.JPanel {

    /** Creates new form PanelProducto */
    public PanelProducto() {
        initComponents();
    }
    public Pedido obtenerPedido(){
        Pedido p1 = new Pedido();
        p1.setCantidad(modelListProducto.getSelectedValue().getId());
        p1.setPrecioUnitario(modelListProducto.getSelectedValue().getPrecioUnitario());
        p1.setDescripcion(modelListProducto.getSelectedValue().getDescripcion());
        p1.setCantidad(0);
        return p1;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modelListProducto1 = new facturacion.gui.ModelListProducto();
        jScrollPaneProducto = new javax.swing.JScrollPane();
        modelListProducto = new javax.swing.JList<>();

        modelListProducto.setModel(modelListProducto1);
        jScrollPaneProducto.setViewportView(modelListProducto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPaneProducto;
    private javax.swing.JList<Producto> modelListProducto;
    private facturacion.gui.ModelListProducto modelListProducto1;
    // End of variables declaration//GEN-END:variables

}
